version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_enviro
    environment:
      POSTGRES_USER: enviro_user
      POSTGRES_PASSWORD: enviro_pass
      POSTGRES_DB: envirosense
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
